### ISSUE TITLE
Implementation in the inspector

### ISSUE THREAD

**Issue by smtabatabaie** [JPBotelho/Unity-Road-Generator#3]
Hi, Thanks very much for this project. Looks very good. I tried to run the project and the demo scene but it doesn't load correctly. Is it possible to put some snapshots from the inspector of Curve object so that I can see what scripts are assigned to it?
Thanks

**Comment by JPBotelho** [comment]
I don't have the metadata anymore, but if I recall correctly just add a SplineComponent script to any object and then the ControlPoints can be just empty transforms IIRC
